{% set version = "0.4.0" %}
package:
  name: feather-format
  version: {{ version }}

source:
  fn: feather-format-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/feather-format/feather-format-{{ version }}.tar.gz
  sha256: a7a0fbc727e1877354d4b4ad83f8e382a249f116241d0ccfc624cac24bddb1a9

build:
  noarch: python
  number: 1003
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas >=0.19.2
    - pyarrow >=0.4.0

test:
  imports:
    - feather

about:
  home: https://github.com/wesm/feather
  license: Apache 2.0
  summary: "Feather: fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow"

extra:
  recipe-maintainers:
    - jjhelmus
    - msarahan
    - wesm
    - cpcloud
    - jreback
    - xhochy
