travis:
  secure:
    BINSTAR_TOKEN: GbaBrlmlc151RcE9/4xj88jH+uALkVtTFdf0DcPrh1qHVQc5Ly6LTFZssZx9gbig/se62b0z6dT5AfjY+uaKLuyujyyUq0LPOecitBOUZTm9ha5B0gH/EbyIs89RjGjR78CWRO6BFYQ3R375zUxUPNUjG65ED4KHf8XEK6Q7f2CtbzPoJVyyyHtenv7RWPR+4L5wZ8d/Hif+JESnoH2AG3FQ6Fp33aw0ulVvzr8Xt07fs3qyFIcxx7sinuPCG9RmwuvE8WfZC0emmFHVdvmecVPJU7M8UHbluV4AZY2lCdefGW9sQ7jvJ4BukBtb6WMu5QLFeDTQeJgYs/OxbvOhmn5u+ZNBVdPRq6pcS+iV1acGbUsKUY4jnO+N4XIY1lI0eTTSNK/jRVRtRx9Yd2WvR5EbCfqcuq4xCXRFzdRkULbHg59e6zfmG+2flItXgA3hZvuoV+arm4m9vL+cRwRNhdgGL2htIdYl6OmzAwo+gQTOjkYug2zb1V6h9xrKFmvBQr3VOZ0Gem6NwOu+3QhxKLCd42z2h2MvVkWZh7rzif6rVy0Z65FCHEtV5BKhXlTp1ERpWLxB25H+em6liUFidg5ba1afLfNckfPpiFN0qBO7XnjEn/KloiKdft4/pu6t5zRRHAUR2sLkuCIdZhY+NqTnsrCT6naa84UEXmkILT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
